# action.yml
name: 'Somef GitHub action'
description: 'A GitHub action to generate codemeta file'
inputs:
  codemeta-file:  # id of input
    description: 'Codemeta file name'
    required: false
    default: 'codemeta.json'
outputs:
  file-exist: # id of output
    description: 'Flag to show whether the file exists'
  generated-codemeta-file: # id of output
    description: 'Name of the generated codemeta file'    
  generation-success: # id of output
    description: 'Whether the codemeta file was generated successfuly'        
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.codemeta-file }}
