on: [push]

jobs:
  somef_job:
    runs-on: ubuntu-latest
    name: Test somef
    steps:
    
    - name: Somef without input
      id: test1
      uses: fdiblen/somef-github-action@main
      with:
        repo-url: "https://github.com/${{ github.repository }}"

    - name: somef with input
      id: test2
      uses: fdiblen/somef-github-action@main
      with:
        codemeta-file: 'test.json'
        repo-url: "https://github.com/${{ github.repository }}"
        
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
